"""Backend package — zero Tkinter, zero PyQt. Pure Python: constants,
file I/O, the ComfyUI client, prompt assembly, LoRA dependency
scanning, and the in-app Guide's text content.

Re-exports every public name so callers can do either
`from backend import load_json` or `from backend.file_manager import
load_json` — both work, the former is just a convenience for the
common cross-module imports UI code will do constantly (e.g. a tab
that needs both file_manager and prompt_builder names).
"""
from backend.constants import (
    DATA_DIR_NAME,
    CATEGORIES,
    TEMPLATES_FILE_NAME,
    CUSTOM_TEMPLATES_FILE_NAME,
    HISTORY_FILE_NAME,
    SETTINGS_FILE_NAME,
    IMAGE_EXTENSIONS,
    IMAGE_STORE_EXT,
    IMAGE_MAX_SIDE,
    LIBRARY_META_EXT,
    LIBRARY_FOLDERS_FILE_NAME,
    FOLDER_PATH_SEP,
    CANONICAL_OUTFITS_FOLDER,
    COMFY_NODE_CLASS_TYPE,
    COMFY_DEFAULT_HOST,
    COMFY_DEFAULT_PORT,
    COMFY_HTTP_TIMEOUT,
    COMFY_POLL_INTERVAL,
    COMFY_POLL_TIMEOUT,
    COMFY_GRAPH_PATH,
    COMFY_LORAS_PATH,
    COMFY_QUEUE_DEBOUNCE_MS,
    COMFY_PREVIEW_MIN_INTERVAL,
    MAX_LORA_SLOTS,
    LORA_NONE_VALUE,
    LORA_STRENGTH_MIN,
    LORA_STRENGTH_MAX,
    COMFY_RESOLUTION_PRESETS,
    GALLERY_THUMB_SIZE,
    GALLERY_CELL_OUTER_WIDTH,
    THEMES,
    CATEGORY_LABELS,
    CATEGORY_ICONS,
    PREFIXES,
    BLOCK_ORDER_LABELS,
    INVALID_FS_CHARS,
    CUSTOM_VAR_PATTERN,
    natural_sort_key,
    sanitize_filename,
)
from backend.comfy_client import ComfyUIError, ComfyUIClient
from backend.guide_content import GUIDE_LANGUAGES, GUIDE_CONTENT, GUIDE_SECTION_ORDER
from backend.file_manager import (
    FileManagerError,
    ImageProcessingError,
    LibraryExportImportError,
    app_dir,
    load_json,
    save_json,
    init_folders,
    library_image_path,
    find_library_image,
    process_and_store_image,
    delete_library_image,
    rename_library_image,
    library_meta_path,
    load_library_meta,
    save_library_meta,
    delete_library_meta,
    rename_library_meta,
    save_folder_map,
    get_entry_folder,
    set_entry_folder,
    remove_entry_folder_entry,
    rename_entry_folder_entry,
    list_all_folders,
    is_protected_folder,
    is_canon_outfit_name,
    move_entries_to_folder,
    create_new_folder,
    rename_folder,
    delete_folder,
    get_file_list,
    list_outfit_options_for_character,
    read_file_content,
    export_library,
    extract_library_zip,
    merge_imported_library,
    resolve_output_folder_for,
    save_comfy_preview_image,
    win_bring_explorer_to_front,
    reveal_file_in_explorer,
)
from backend.prompt_builder import (
    parse_custom_template,
    generate_custom_prompt,
    build_style_block,
    build_characters_block,
    build_scenario_block,
    build_tools_block,
    generate_standard_prompt,
    collect_active_library_loras,
    compute_lora_autofill,
)
from backend.lora_deps import (
    apply_lora_candidate,
    find_lora_candidates,
    scan_library_lora_dependencies,
)

__all__ = [
    # constants
    "DATA_DIR_NAME", "CATEGORIES", "TEMPLATES_FILE_NAME", "CUSTOM_TEMPLATES_FILE_NAME",
    "HISTORY_FILE_NAME", "SETTINGS_FILE_NAME", "IMAGE_EXTENSIONS", "IMAGE_STORE_EXT",
    "IMAGE_MAX_SIDE", "LIBRARY_META_EXT", "LIBRARY_FOLDERS_FILE_NAME", "FOLDER_PATH_SEP",
    "CANONICAL_OUTFITS_FOLDER", "COMFY_NODE_CLASS_TYPE", "COMFY_DEFAULT_HOST",
    "COMFY_DEFAULT_PORT", "COMFY_HTTP_TIMEOUT", "COMFY_POLL_INTERVAL", "COMFY_POLL_TIMEOUT",
    "COMFY_GRAPH_PATH", "COMFY_LORAS_PATH", "COMFY_QUEUE_DEBOUNCE_MS",
    "COMFY_PREVIEW_MIN_INTERVAL", "MAX_LORA_SLOTS",
    "LORA_NONE_VALUE", "LORA_STRENGTH_MIN", "LORA_STRENGTH_MAX", "COMFY_RESOLUTION_PRESETS",
    "GALLERY_THUMB_SIZE", "GALLERY_CELL_OUTER_WIDTH", "THEMES", "CATEGORY_LABELS",
    "CATEGORY_ICONS", "PREFIXES", "BLOCK_ORDER_LABELS", "INVALID_FS_CHARS",
    "CUSTOM_VAR_PATTERN", "natural_sort_key", "sanitize_filename",
    # comfy_client
    "ComfyUIError", "ComfyUIClient",
    # guide_content
    "GUIDE_LANGUAGES", "GUIDE_CONTENT", "GUIDE_SECTION_ORDER",
    # file_manager
    "FileManagerError", "ImageProcessingError", "LibraryExportImportError",
    "app_dir", "load_json", "save_json", "init_folders",
    "library_image_path", "find_library_image", "process_and_store_image",
    "delete_library_image", "rename_library_image",
    "library_meta_path", "load_library_meta", "save_library_meta",
    "delete_library_meta", "rename_library_meta",
    "save_folder_map", "get_entry_folder", "set_entry_folder",
    "remove_entry_folder_entry", "rename_entry_folder_entry",
    "list_all_folders", "is_protected_folder", "is_canon_outfit_name",
    "move_entries_to_folder", "create_new_folder", "rename_folder", "delete_folder",
    "get_file_list", "list_outfit_options_for_character", "read_file_content",
    "export_library", "extract_library_zip", "merge_imported_library",
    "resolve_output_folder_for", "save_comfy_preview_image",
    "win_bring_explorer_to_front", "reveal_file_in_explorer",
    # prompt_builder
    "parse_custom_template", "generate_custom_prompt",
    "build_style_block", "build_characters_block", "build_scenario_block", "build_tools_block",
    "generate_standard_prompt", "collect_active_library_loras", "compute_lora_autofill",
    # lora_deps
    "apply_lora_candidate", "find_lora_candidates", "scan_library_lora_dependencies",
]
