"""QSS stylesheet generator — turns a `backend.constants.THEMES[name]` color
dict into a full application stylesheet string.

There is no Tkinter equivalent to port here 1:1: the original configured
~15 individual ttk.Style() rules scattered across `apply_theme`/
`refresh_themed_widgets`. QSS covers the same ground in one place, the
idiomatic Qt way, so this module is a clean reimplementation against the
same color tokens rather than a line-by-line port. Every widget class the
app actually uses gets its own block below; nothing here references a
backend value other than the color dict.

`.accent` / `.danger` / `.ghost` are QPushButton object-name variants
(`button.setObjectName("accent")`, etc.) — the original's
"Accent.TButton" / "Danger.TButton" / "Ghost.TButton" ttk styles.
"""
from PyQt6.QtWidgets import QApplication

from backend.constants import THEMES


def build_qss(theme) -> str:
    """Generates a full application QSS string from a color dict.

    `theme` can be either a `THEMES` key (str — looked up as before,
    still raising KeyError for an unknown name, no silent fallback to
    mask a typo'd theme name) or an already-built colors dict, which is
    how Session 39's derived "Custom" palette gets in here without
    needing a matching `THEMES` entry."""
    c = THEMES[theme] if isinstance(theme, str) else theme
    label = theme if isinstance(theme, str) else "custom"

    return f"""
/* ============================================================
   PromptForge — {label} theme
   Generated by ui/theme.py:build_qss() from backend.constants.THEMES
   ============================================================ */

QMainWindow, QWidget {{
    background-color: {c['bg']};
    color: {c['fg']};
    font-family: "Segoe UI", sans-serif;
    font-size: 13px;
}}

QToolTip {{
    background-color: {c['bg_card']};
    color: {c['fg']};
    border: 1px solid {c['border']};
    border-radius: 6px;
    padding: 4px 8px;
}}

/* ---------------------------- Tabs ---------------------------- */
QTabWidget::pane {{
    border: 1px solid {c['border']};
    border-radius: 8px;
    background-color: {c['bg']};
    top: -1px;
}}
QTabBar::tab {{
    background-color: {c['bg_alt']};
    color: {c['fg_dim']};
    border: 1px solid {c['border']};
    border-bottom: none;
    border-top-left-radius: 8px;
    border-top-right-radius: 8px;
    padding: 7px 18px;
    margin-right: 2px;
}}
QTabBar::tab:selected {{
    background-color: {c['bg']};
    color: {c['fg']};
    border-color: {c['accent']};
}}
QTabBar::tab:hover:!selected {{
    color: {c['fg']};
}}

/* Session 20 follow-up: your annotated screenshot flagged the
   Positive/Negative selected tab as reading "inverted" relative to
   its neighbor -- root cause was two stacked mismatches, not one:
   (1) the generic rule above colors *every* border side accent-blue
   on selection, which nothing else in the app does (other fields
   only get an accent border on :focus) -- reads as a heavier, oddly
   highlighted box instead of a normal selected tab; (2) the selected
   tab's own background (`bg`, the page color) no longer matched its
   pane's background (`bg_card`, since Session 20's card-consistency
   pass), a mismatch this app never had before that pass. Scoped to
   `#PromptOutputTabs` specifically since it's the only QTabWidget in
   the app -- neutral border like every other field, background
   matched to the pane, and a slim accent top-edge (not a full box)
   carries the "this one's selected" signal instead. */
QTabWidget#PromptOutputTabs QTabBar::tab:selected {{
    background-color: {c['bg_alt']};
    color: {c['fg']};
    border-color: {c['border']};
    border-top: 2px solid {c['accent']};
    padding-top: 6px;
    font-weight: 600;
}}

/* --------------------------- Buttons --------------------------- */
QPushButton, QToolButton {{
    background-color: {c['bg_card']};
    color: {c['fg']};
    border: 1px solid {c['border']};
    border-radius: 8px;
    padding: 6px 14px;
}}
QPushButton:hover, QToolButton:hover {{
    border-color: {c['accent']};
}}
QPushButton:pressed, QToolButton:pressed {{
    background-color: {c['bg_alt']};
}}
QPushButton:disabled, QToolButton:disabled {{
    color: {c['fg_dim']};
    border-color: {c['border']};
}}

QPushButton#accent {{
    background-color: {c['accent']};
    color: {c['accent_text']};
    border: none;
    font-weight: 600;
}}
QPushButton#accent:hover {{
    background-color: {c['accent_hover']};
}}
QPushButton#accent:disabled {{
    background-color: {c['border']};
    color: {c['fg_dim']};
}}

QPushButton#danger {{
    background-color: transparent;
    color: {c['danger']};
    border: 1px solid {c['danger']};
}}
QPushButton#danger:hover {{
    background-color: {c['danger']};
    color: {c['accent_text']};
    border-color: {c['danger_hover']};
}}
QPushButton#danger:disabled {{
    background-color: transparent;
    color: {c['fg_dim']};
    border-color: {c['border']};
}}

QPushButton#ghost {{
    background-color: transparent;
    border: none;
    color: {c['fg_dim']};
    padding: 4px 8px;
}}
QPushButton#ghost:hover {{
    color: {c['fg']};
}}
QPushButton#ghost:disabled {{
    color: {c['fg_dim']};
}}

/* QToolButton used as a CollapsibleSection header — flat, no border
   chrome, arrow + text laid out beside each other. */
QToolButton#CollapsibleHeader {{
    background-color: transparent;
    border: none;
    color: {c['fg']};
    font-weight: 600;
    padding: 2px 0px;
    text-align: left;
}}
QToolButton#CollapsibleHeader:hover {{
    color: {c['accent']};
}}

/* Session 17.5: fixed-position toggle handle pinned to
   CollapsibleRail's left edge — bigger and more visually distinct
   than the old header-row button so it's easy to find and click,
   never shares a row with a label that can disappear. */
QToolButton#RailHandle {{
    background-color: {c['bg_card']};
    border: 1px solid {c['border']};
    border-radius: 8px;
    color: {c['fg_dim']};
    font-weight: 700;
    font-size: 13px;
    padding: 0px;
}}
QToolButton#RailHandle:hover {{
    background-color: {c['accent']};
    border-color: {c['accent']};
    color: white;
}}

/* ----------------------- Inputs / fields ----------------------- */
QLineEdit, QPlainTextEdit, QTextEdit, QSpinBox, QDoubleSpinBox {{
    background-color: {c['bg_input']};
    color: {c['fg']};
    border: 1px solid {c['border']};
    border-radius: 8px;
    padding: 5px 8px;
    selection-background-color: {c['select_bg']};
}}
QLineEdit:focus, QPlainTextEdit:focus, QTextEdit:focus,
QSpinBox:focus, QDoubleSpinBox:focus {{
    border-color: {c['accent']};
}}
QLineEdit:disabled, QPlainTextEdit:disabled {{
    color: {c['fg_dim']};
}}

QComboBox {{
    background-color: {c['bg_input']};
    color: {c['fg']};
    border: 1px solid {c['border']};
    border-radius: 8px;
    padding: 5px 8px;
}}
QComboBox:hover {{
    border-color: {c['accent']};
}}
QComboBox::drop-down {{
    border: none;
    width: 22px;
}}
QComboBox QAbstractItemView {{
    background-color: {c['bg_card']};
    color: {c['fg']};
    border: 1px solid {c['border']};
    selection-background-color: {c['select_bg']};
    outline: none;
}}

/* AutocompleteCombobox — Session 25.4 rewrite: a plain QFrame housing
   a borderless QLineEdit + arrow QToolButton (no QComboBox involved
   anymore, see ui/widgets/autocomplete.py for why). Give the frame the
   same look QComboBox got for free before. */
QFrame#AutocompleteCombobox {{
    background-color: {c['bg_input']};
    border: 1px solid {c['border']};
    border-radius: 8px;
}}
QFrame#AutocompleteCombobox:hover {{
    border-color: {c['accent']};
}}
QFrame#AutocompleteCombobox:focus {{
    border-color: {c['accent']};
}}
QLineEdit#AutocompleteLineEdit {{
    background: transparent;
    border: none;
    border-radius: 0px;
    padding: 3px 0px;
    color: {c['fg']};
}}
QToolButton#AutocompleteArrow {{
    background: transparent;
    border: none;
    color: {c['fg_dim']};
    padding: 0px 2px;
}}
QToolButton#AutocompleteArrow:hover {{
    color: {c['accent']};
}}

/* AutocompleteCombobox's own popup (QFrame#AutocompletePopup wrapping
   a QListWidget) — see ui/widgets/autocomplete.py. */
QFrame#AutocompletePopup {{
    background-color: {c['bg_card']};
    border: 1px solid {c['accent']};
    border-radius: 6px;
}}
QListWidget {{
    background-color: {c['bg_card']};
    color: {c['fg']};
    border: none;
    outline: none;
}}
QListWidget::item {{
    padding: 4px 8px;
}}
QListWidget::item:selected {{
    background-color: {c['accent']};
    color: {c['accent_text']};
}}

QLabel {{
    background-color: transparent;
    color: {c['fg']};
}}
QLabel#dim {{
    color: {c['fg_dim']};
}}
/* Session 20 follow-up: heading label used by `_build_card` (Style/
   Characters/Scenario/Tools/Seed/Resolution) -- replaces QGroupBox's
   native title, which left a visible gap between the title text and
   the card border under this style, reading as a floating label
   rather than a card header. */
QLabel#CardHeading {{
    color: {c['fg']};
    font-weight: 600;
}}

/* --------------------------- GroupBox --------------------------- */
QGroupBox {{
    background-color: {c['bg_card']};
    border: 1px solid {c['border']};
    border-radius: 8px;
    margin-top: 14px;
    padding: 10px;
    font-weight: 600;
}}
QGroupBox::title {{
    subcontrol-origin: margin;
    left: 10px;
    padding: 0 6px;
    color: {c['fg']};
}}
/* Session 15: tighter variant for Builder's numbered Style/Characters/
   Scenario/Tools boxes -- same chrome, less padding, so the column
   fits more content before it needs to scroll. */
QGroupBox#CompactGroup {{
    margin-top: 12px;
    padding: 6px 8px 8px 8px;
}}

/* --------------------------- Card frame --------------------------- */
/* Used for the Builder tab's character/tool slot rows — port of the
   original's "Card.TFrame" ttk style. Session 20: selector dropped its
   `QFrame` type qualifier (`#Card` instead of `QFrame#Card`) so the
   same rule also backs `CollapsibleSection(card=True)` (a QWidget, not
   a QFrame) -- e.g. the Template panel header -- without needing a
   second, duplicate rule to keep in sync. */
#Card {{
    background-color: {c['bg_alt']};
    border: 1px solid {c['border']};
    border-radius: 8px;
    padding: 8px;
}}

/* Session 20 step 3: explicit, high-specificity background for the
   Positive/Negative prompt output boxes -- gives them their own
   selector (rather than relying solely on the generic QPlainTextEdit
   rule above) so this specific pair can never silently pick up a
   mismatched background regardless of container/state. Matches every
   other input field's background (`bg_input`) in both themes. */
QPlainTextEdit#PromptOutput {{
    background-color: {c['bg_input']};
    color: {c['fg']};
    border: 1px solid {c['border']};
    border-radius: 8px;
}}
QPlainTextEdit#PromptOutput:focus {{
    border-color: {c['accent']};
}}

/* Session 20 step 3 (corrected in the follow-up fix below): the tab
   pane behind the Positive/Negative pair used to inherit the page
   background (`bg`), a visible step down from the card-colored chrome
   around every other block -- match the *actual* card token,
   `bg_alt` (what `#Card`/`_build_card` actually paints, confirmed
   against your Scenario-card reference screenshot -- `bg_card` was
   the wrong token here, one step too light/dark in the dark theme
   even though the two happen to be identical white in light theme,
   which is why this specific mismatch only showed up once you sent a
   dark-theme screenshot) so the whole tab widget reads as one more
   card, same language as Style/Characters/Scenario/Tools. */
QTabWidget#PromptOutputTabs::pane {{
    border: 1px solid {c['border']};
    border-radius: 8px;
    background-color: {c.get('bg_alt_solid', c['bg_alt'])};
    top: -1px;
}}
/* Session 20 — THIRD fix: the actual root cause of the "Copy button
   sits on a mismatched backdrop" bug. `positive_tab`/`_negative_tab`
   (the plain QWidget each tab page actually is) sit *inside* the pane
   and fully cover it -- as an unstyled QWidget, each one was painted
   by the generic `QMainWindow, QWidget {{ background-color: bg }}`
   rule at the top of this file, i.e. the *page* background, not the
   pane's `bg_alt` behind it. The pane's own background-color (fixed
   above) was therefore never actually visible anywhere except a
   1px sliver at its very edge -- confirmed by your screenshot markup,
   which circled exactly the margin strip around the Copy button
   (`pos_layout`'s 6px content margins) where this opaque child
   widget, not the pane, is what's on screen. Both page widgets get
   `WA_StyledBackground` + this explicit `bg_alt` rule so they stop
   masking the pane underneath. */
QWidget#PromptOutputPage {{
    background-color: {c.get('bg_alt_solid', c['bg_alt'])};
}}
/* Session 40.1 follow-up: both this rule and the ::pane rule above
   deliberately use `bg_alt_solid` (falls back to plain `bg_alt` for
   every context that doesn't set it, i.e. every theme except Custom
   with Card opacity active) rather than the Card-opacity-affected
   `bg_alt`. Both are fully hidden behind the actual `QPlainTextEdit`
   in normal use (Session 20's own note above already established that
   only a slim margin sliver of the page shows at all) -- with a
   translucent `bg_alt` here too, that sliver plus the text edit
   itself would stack two independent alpha blends on top of each
   other, which compounds (each pass lets through less of the true
   backdrop than either alone) and made the Positive/Negative box read
   as barely-translucent at all next to the single-layer Style/
   Characters/Scenario cards -- confirmed from a real screenshot, not
   caught by this environment's headless testing. Keeping this specific
   layer solid gives the box exactly one translucent layer (the text
   edit's own `bg_input`), matching every other card's blend strength. */


/* --------------------------- TreeWidget --------------------------- */
QTreeWidget {{
    background-color: {c['tree_bg']};
    alternate-background-color: {c['tree_alt']};
    color: {c['fg']};
    border: 1px solid {c['border']};
    border-radius: 8px;
    outline: none;
}}
QTreeWidget::item {{
    padding: 3px 2px;
}}
QTreeWidget::item:selected {{
    background-color: {c['select_bg']};
    color: {c['fg']};
}}
QHeaderView::section {{
    background-color: {c['bg_alt']};
    color: {c['fg_dim']};
    border: none;
    border-bottom: 1px solid {c['border']};
    padding: 4px 6px;
}}

/* --------------------------- Splitter --------------------------- */
/* Session 29: the default 2px hairline read as a stray line in the
   middle of the page rather than a deliberate drag control. Widened to
   a real grab target and given a hover-accent so it's discoverable at
   a glance, matching the spirit of CollapsibleRail's own handle. */
QSplitter::handle {{
    background-color: {c['border']};
}}
QSplitter::handle:horizontal {{
    width: 6px;
}}
QSplitter::handle:vertical {{
    height: 6px;
}}
QSplitter::handle:hover {{
    background-color: {c['accent']};
}}

/* --------------------------- ScrollArea / ScrollBar ------------- */
QScrollArea {{
    border: none;
    background-color: transparent;
}}
QScrollBar:vertical {{
    background: transparent;
    width: 12px;
    margin: 2px;
}}
QScrollBar::handle:vertical {{
    background: {c['border']};
    border-radius: 5px;
    min-height: 24px;
}}
QScrollBar::handle:vertical:hover {{
    background: {c['fg_dim']};
}}
QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{
    height: 0px;
}}
QScrollBar:horizontal {{
    background: transparent;
    height: 12px;
    margin: 2px;
}}
QScrollBar::handle:horizontal {{
    background: {c['border']};
    border-radius: 5px;
    min-width: 24px;
}}
QScrollBar::handle:horizontal:hover {{
    background: {c['fg_dim']};
}}
QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {{
    width: 0px;
}}

/* --------------------------- Slider --------------------------- */
QSlider::groove:horizontal {{
    background: {c['border']};
    height: 4px;
    border-radius: 2px;
}}
QSlider::handle:horizontal {{
    background: {c['accent']};
    width: 14px;
    height: 14px;
    margin: -6px 0;
    border-radius: 7px;
}}
QSlider::handle:horizontal:hover {{
    background: {c['accent_hover']};
}}
QSlider::sub-page:horizontal {{
    background: {c['accent']};
    border-radius: 2px;
}}

/* --------------------------- ProgressBar ------------------------ */
QProgressBar {{
    background-color: {c['bg_input']};
    border: 1px solid {c['border']};
    border-radius: 8px;
    text-align: center;
    color: {c['fg']};
}}
QProgressBar::chunk {{
    background-color: {c['accent']};
    border-radius: 7px;
}}

/* --------------------------- Dialog --------------------------- */
QDialog {{
    background-color: {c['bg']};
    color: {c['fg']};
}}

/* --------------------------- CheckBox / RadioButton -------------- */
QCheckBox, QRadioButton {{
    color: {c['fg']};
    spacing: 6px;
}}
QCheckBox::indicator, QRadioButton::indicator {{
    width: 15px;
    height: 15px;
    border: 1px solid {c['border']};
    border-radius: 4px;
    background-color: {c['bg_input']};
}}
QRadioButton::indicator {{
    border-radius: 8px;
}}
QCheckBox::indicator:checked, QRadioButton::indicator:checked {{
    background-color: {c['accent']};
    border-color: {c['accent']};
}}

/* --------------------------- Gallery --------------------------- */
/* One cell in the Gallery tab's grid (ui/tabs/gallery_tab.py). The
   thumbnail QLabel itself is styled inline (it needs a per-theme
   background behind transparent PNGs), but the card chrome around it
   lives here like every other themed surface. */
QFrame#GalleryCell {{
    background-color: {c['bg_card']};
    border: 1px solid {c['border']};
    border-radius: 10px;
}}
QFrame#GalleryCell:hover {{
    border-color: {c['accent']};
}}
/* Hover-only overlay buttons (reveal / full view) — small, round,
   semi-opaque so they read as floating controls over the thumbnail
   rather than ordinary toolbar buttons. */
QPushButton#GalleryOverlayBtn {{
    background-color: rgba(0, 0, 0, 0.55);
    color: #ffffff;
    border: none;
    border-radius: 14px;
    padding: 0px;
}}
QPushButton#GalleryOverlayBtn:hover {{
    background-color: {c['accent']};
}}

/* --------------------------- Sidebar (Session 14, polished 14.5) -- */
QFrame#SidebarRail {{
    background-color: {c['bg_alt']};
    border: none;
    border-right: 1px solid {c['border']};
}}
QPushButton#SidebarNav {{
    background-color: transparent;
    border: none;
    border-left: 3px solid transparent;
    border-radius: 0px;
    color: {c['fg_dim']};
    text-align: center;
    padding: 6px 2px;
    font-weight: 500;
    font-size: 11px;
}}
QPushButton#SidebarNav:hover {{
    color: {c['fg']};
    background-color: {c['bg_card']};
}}
QPushButton#SidebarNav:checked {{
    color: {c['fg']};
    background-color: {c['bg_card']};
    border-left: 3px solid {c['accent']};
    font-weight: 600;
}}
/* Session 48.2: the standalone pipeline-mode switch that replaced the
   plain "⚡" brand label at the top of the sidebar -- deliberately its
   own object name, not #SidebarNav, since it's not a page-navigation
   button (not checkable, not in the exclusive nav QButtonGroup) and
   shouldn't pick up SidebarNav's `:checked` accent-border look. */
QPushButton#SidebarModeSwitch {{
    background-color: transparent;
    border: none;
    border-radius: 6px;
    color: {c['fg']};
    text-align: center;
    padding: 4px 2px;
    font-weight: 600;
    font-size: 11px;
}}
QPushButton#SidebarModeSwitch:hover {{
    background-color: {c['bg_card']};
    color: {c['accent']};
}}
QFrame#SidebarDivider {{
    background-color: {c['border']};
    max-height: 1px;
    border: none;
    margin: 4px 6px;
}}
QFrame#SidebarComfyFooter {{
    background-color: {c['bg_card']};
    border: 1px solid {c['border']};
    border-radius: 8px;
}}
/* Session 14.5 step 2: this used to be a full-width #accent button
   sized like a primary action — shrunk to a small, secondary-weight
   control so the footer's status line reads as the primary content,
   not the button under it. */
QPushButton#SidebarComfyBtn {{
    background-color: transparent;
    color: {c['fg_dim']};
    border: 1px solid {c['border']};
    border-radius: 6px;
    padding: 3px 6px;
    font-size: 11px;
}}
QPushButton#SidebarComfyBtn:hover {{
    color: {c['fg']};
    border-color: {c['accent']};
}}
QPushButton#SidebarComfyBtn:disabled {{
    color: {c['fg_dim']};
}}

/* --------------------------- Context menus --------------------- */
/* Session 44: QMenu doesn't inherit a parent widget's QSS the way most
   other widgets do -- it was rendering with the bare platform default
   (native grey/selection-blue on Windows), the one place left in the
   app that didn't read the accent color. Global rule (not scoped to
   any #objectName) so it covers every QMenu in the app -- today that's
   just the Library tree's right-click menu (library_tab.py), including
   its "Move to..." submenu, which is also a QMenu -- and any future one
   for free, with no per-instance stylesheet needed. */
QMenu {{
    background-color: {c['bg_card']};
    color: {c['fg']};
    border: 1px solid {c['border']};
    border-radius: 8px;
    padding: 4px;
}}
QMenu::item {{
    background-color: transparent;
    padding: 6px 24px 6px 12px;
    border-radius: 6px;
}}
QMenu::item:selected {{
    background-color: {c['accent']};
    color: {c['accent_text']};
}}
QMenu::item:disabled {{
    color: {c['fg_dim']};
}}
QMenu::separator {{
    height: 1px;
    background-color: {c['border']};
    margin: 4px 6px;
}}
QMenu::indicator {{
    width: 14px;
    height: 14px;
}}

/* --------------------------- Status accents -------------------- */
QLabel#success {{ color: {c['success']}; }}
QLabel#danger  {{ color: {c['danger']}; }}
QLabel#warn    {{ color: {c['warn']}; }}
""".strip()


def apply_theme(app: QApplication, theme) -> None:
    """Generates and applies the stylesheet for `theme` (a `THEMES` key
    or a colors dict — see `build_qss`) to the whole application in one
    call — `app.setStyleSheet(...)` cascades to every widget, current
    and future, the same way the original's `apply_theme`/
    `refresh_themed_widgets` pair updated every ttk.Style rule at once
    on a dark/light toggle."""
    app.setStyleSheet(build_qss(theme))
